name: project_environment
channels:
 - defaults
dependencies:
 - python=3.7.6
 - pip=20.2
 - pip:
  - azureml-sdk==0.1.0.*
  - azureml-designer-core==0.0.54
  - scikit-learn==0.24.*
  - scipy==1.6.2
  - matplotlib==3.4.2
  - azureml-dataset-runtime[fuse,pandas]
  - --index-url https://azuremlsdktestpypi.azureedge.net/dev/aml/office/134157926D8F
  - --extra-index-url https://pypi.org/simple