name: 'Validating Azure Machine Learning componets'
description: 'Validates Azure Machine Learning components before publishing'
inputs:
  component-spec:
    description: 'Component specification file. This parameters supports willcards'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-dependecies
      shell: bash
      run: |
        echo "::debug::Installing Azure CLI"
        if [ -x "$(command -v az)" ]; then
          echo "::debug::Azure CLI is already installed"
        else
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi

        echo "::debug::Installing azure-cli-ml extension with components support"
        if [[ $(az extension show --name azure-cli-ml) ]]; then
          echo "::debug::azure-cli-ml extension is already installed."
        else
          az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/componentsdk/azure_cli_ml-0.9.1-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/componentsdk/0.9.1 --yes --verbose
        fi
        
    - id: validate
      shell: bash
      run: |
        echo "::debug::Attaching folder for workspace ${{ inputs.workspace }} at resource group ${{ inputs.resource-group }}"
        az ml folder attach --workspace-name ${{ inputs.workspace }} --resource-group ${{ inputs.resource-group }}

        COMP_FILES=$(find ${{ inputs.component-spec }} -exec realpath --relative-to=${{ github.workspace }} {} \;)

        for COMP in $COMP_FILES
        do
          COMPONENT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_REF##*/}/$COMP
          echo "::debug::Validating file at $COMPONENT_URL"
          az ml component validate --file $COMPONENT_URL 
        done

