name: 'Validating Azure Machine Learning componets'
description: 'Validates Azure Machine Learning components before publishing'
inputs:
  component-spec:
    description: 'Component specification file. This parameters supports willcards'
    required: true
  resource-group:
    description: The resource group
    required: true
  workspace:
    description: Azure ML workspace
    required: true
runs:
  using: "composite"
  steps:        
    - id: validate
      shell: bash
      run: |
        COMP_FILES=$(find ${{ inputs.component-spec }} -exec realpath --relative-to=${{ github.workspace }} {} \;)

        for COMP in $COMP_FILES
        do
          COMPONENT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_REF##*/}/$COMP
          echo "::debug::Validating file at $COMPONENT_URL"
          az ml component validate --file $COMPONENT_URL -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }}
        done

