name: 'Attaching Azure Machine Learning workspace'
description: 'Attaches an Azure Machine Learning workspace to the current run'
inputs:
  resource-group:
    description: The resource group
    required: true
  workspace:
    description: Azure ML workspace to be attached
    required: true
runs:
  using: "composite"
  steps:
    - id: install-dependecies
      shell: bash
      run: |
        echo "::debug::Installing Azure CLI"
        if [ -x "$(command -v az)" ]; then
          echo "::debug::Azure CLI is already installed"
        else
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi

        echo "::debug::Installing azure-cli-ml extension with components support"
        if [[ $(az extension show --name azure-cli-ml) ]]; then
          echo "::debug::azure-cli-ml extension is already installed."
        else
          az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/componentsdk/azure_cli_ml-0.9.1-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/componentsdk/0.9.1 --yes --verbose
        fi

    - id: attach
      shell: bash
      run: |
        echo "::debug::Attaching folder for workspace ${{ inputs.workspace }} at resource group ${{ inputs.resource-group }}"
        az ml folder attach --workspace-name ${{ inputs.workspace }} --resource-group ${{ inputs.resource-group }}