name: 'Publishing Azure Machine Learning componets'
description: 'Publishes Azure Machine Learning  components'
inputs:
  component-spec:
    description: 'Component specification file. This parameters supports willcards'
    required: true
  resource-group:
    description: The resource group
    required: true
  workspace:
    description: Azure ML workspace
    required: true
runs:
  using: "composite"
  steps:
    - id: publish
      shell: bash
      run: |
        INSTALLED=$(az ml component list -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }} | jq .[].name)
        COMP_FILES=$(find ${{ inputs.component-spec }} -exec realpath --relative-to=${{ github.workspace }} {} \;)

        for COMP in $COMP_FILES
        do
          COMPONENT_NAME=$(yq -r .name $COMP)
          COMPONENT_VERSION=$(yq -r .version $COMP)
          COMPONENT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_REF##*/}/$COMP

          echo "::debug::Verifying component installation for $COMPONENT_NAME @ $COMPONENT_VERSION"
          COMPONENT_INSTALLED=$(az ml component list -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }} | jq -r --arg COMPONENT_NAME $COMPONENT_NAME '.[].name | select(contains($COMPONENT_NAME))')

          echo "::debug::Installing component $COMPONENT_NAME @ $COMPONENT_VERSION"
          if [ -n "$COMPONENT_INSTALLED" ];
          then
            az ml component create --file $COMP -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }}

            echo "::debug::Updating default version for component $COMPONENT_NAME to $COMPONENT_VERSION"
            az ml component update --name "$COMPONENT_NAME" --version $COMPONENT_VERSION --label default -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }}
          else
            az ml component create --file $COMP -g ${{ inputs.resource-group }} -w ${{ inputs.workspace }}
          fi
        done