name: 'Publishing componets'
description: 'Publishes Azure ML components'
inputs:
  resource-group:
    description: The resource group
    required: true
  workspace:
    description: 'Azure ML workspace name where components will be published'
    required: true
  component-spec:
    description: 'Component specification file. This parameters supports willcards'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-azureml
      shell: bash
      run: |
        echo "::debug::Installing Azure CLI"
        if test -f "az"; then
          echo "::debug::Azure CLI is installed"
        else
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi

        echo "::debug::Installing azureml-cli with components support"
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/componentsdk/azure_cli_ml-0.9.1-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/componentsdk/0.9.1 --yes --verbose
        
        echo "::debug::Installing yq"
        pip install yq==2.12.2
    - id: publish
      shell: bash
      run: |
        echo "::debug::Attaching folder for workspace ${{ inputs.workspace }} at resource group ${{ inputs.resource-group }}"
        az ml folder attach --workspace-name ${{ inputs.workspace }} --resource-group ${{ inputs.resource-group }}

        INSTALLED=$(az ml component list | jq .[].name)

        COMP_FILES=$(find ${{ inputs.component-spec }} -exec realpath --relative-to=${{ github.workspace }} {} \;)

        for COMP in $COMP_FILES
        do
          COMPONENT_NAME=$(yq .name $COMP)
          COMPONENT_VERSION=$(yq .version $COMP)
          COMPONENT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_REF##*/}/$COMP

          echo "::debug::Verifying component installation for $COMPONENT_NAME @ $COMPONENT_VERSION"
          COMPONENT_INSTALLED=$(az ml component list | jq  '.[].name | select(contains("'"$COMPONENT_NAME"'"))')

          echo "::debug::Installing component $COMPONENT_NAME @ $COMPONENT_VERSION"
          if [[ $COMPONENT_INSTALLED ==  '$COMPONENT_NAME' ]];
          then
            az ml component create --file $COMP 

            echo "::debug::Updating default version for component $COMPONENT_NAME to $COMPONENT_VERSION"
            az ml component update --name "$COMPONENT_NAME" --version $COMPONENT_VERSION --label default
          else
            az ml component create --file $COMP 
          fi
        done