name: CI

on:
  push:
    paths:
    - '.github/**'
    - 'modules/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMPONENTS_PATH: modules
      WORKSPACE: aa-ml-aml-showroom-ws
      RESOURE_GROUP: Analytics.Aml.Experiments.Workspaces

    steps:
      - uses: actions/checkout@v2

      - name: Installing Azure ML CLI
        uses: ./.github/actions/aml-cli-install
        with:
          component-support: true
          cli-version: '2.29.0'
          ml-min-version: '2.0'

      - name: Logining in into Azure
        uses: Azure/login@v1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}

      - name: Running test on modules
        uses: ./.github/actions/pytest-run
        with:
          test-folder: tests

      - name: Validating Azure ML componets
        uses: ./.github/actions/aml-component-validate
        with:
          component-spec: ${{ env.COMPONENTS_PATH }}/*/*.yaml
          resource-group: ${{ env.RESOURE_GROUP }}
          workspace: ${{ env.WORKSPACE }}
