name: CI

on:
  push:
    paths:
    - '.github/**'
    - 'modules/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMPONENTS_PATH: modules
      WORKSPACE: aa-ml-aml-showroom-ws

    steps:
      - uses: actions/checkout@v2

      - name: Logining in into Azure
        uses: Azure/login@v1
        env:
          CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}

      - name: Validating componets
        uses: ./.github/actions/aml-validate-component
        with:
          workspace: ${{ env.WORKSPACE }}
          component-spec: ${{ env.COMPONENTS_PATH }}/*/*.yaml
